### ISSUE TITLE
Flat Flex Connector Relocation

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/SolarPanels#12]
Redesign the flat flex cable so it is easier to route.

- [x] Orient FFC connectors on the X and Z boards so they point towards +Y
- [x] Move FFC connector on -Y board so it doesn't interfere with battery box. Orient it so it points towards one of the outside edges. Probably best to have it point towards one of the X edges since the Z sides are more crowded.
- [x] Update 3D model with all revised boards and route flat flex cable - minimize bends/contorsions
- [ ] Revise flat flex cable circuit design

**Comment by NeilKhera** [comment]
Relocation addressed in #15
