### ISSUE TITLE
Burn wire holes on +Y board interfere with Z board

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/SolarPanels#14]
Burn wire holes on +Y board should be shifted in to avoid interfering with Z board overlap. Shift in (pcb coordinates) 1mm in -X direction.

<img width="674" alt="Screen Shot 2022-02-22 at 8 57 02 PM" src="https://user-images.githubusercontent.com/29437542/155250012-34a2c56b-c5ab-4302-8455-1f784a620dbf.png">

**Comment by NeilKhera** [comment]
Addressed in #15
