### ISSUE TITLE
Battery harness redesign

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/SolarPanels#8]
The current battery harness is bulky and time consuming to build, mostly due to having to route wires between each set of batteries. A revision of the battery harness, possibly including some small PCBs, would allow for easier construction and testing of the batteries.

**Comment by jbwillis** [comment]
Some more thoughts and questions on how to do this.

- [ ] Could we use only one type of battery? The more square ones are 150 mAh and seem to fit into the space better.
- [ ] Solder two batteries to a little circuit board that plugs into the -Y board?

**Comment by jbwillis** [comment]
Another idea - solder two batteries to the bottom half of each of the X and Z boards, getting rid of the battery donut entirely. This would require adding another power signal to the FFC to take power from the batteries to the sep switches. Bad idea? maybe.

**Comment by NeilKhera** [comment]
Solved with Revision B
